INSERT INTO products (product_name, price, category) VALUES
('Random Book', 19.99, 'BOOKS'),
('Organic Apples', 2.99, 'GROCERY'),
('Latest Laptop', 999.99, 'ELECTRONICS'),
('Mystery Novel', 12.99, 'BOOKS'),
('Fresh Milk', 1.99, 'GROCERY'),
('Gaming Console', 399.99, 'ELECTRONICS'),
('Cookbook', 14.99, 'BOOKS'),
('Whole Wheat Bread', 2.49, 'GROCERY'),
('Smart TV', 499.99, 'ELECTRONICS'),
('Science Fiction Novel', 16.99, 'BOOKS'),
('Organic Carrots', 1.99, 'GROCERY'),
('Gaming Headset', 99.99, 'ELECTRONICS'),
('Self-Help Book', 18.99, 'BOOKS'),
('Yogurt', 1.49, 'GROCERY'),
('Smartwatch', 299.99, 'ELECTRONICS'),
('Historical Fiction Novel', 15.99, 'BOOKS'),
('Organic Spinach', 2.99, 'GROCERY'),
('Gaming Mouse', 29.99, 'ELECTRONICS'),
('Romance Novel', 11.99, 'BOOKS'),
('Eggs', 2.49, 'GROCERY'),
('Gaming Keyboard', 79.99, 'ELECTRONICS'),
('Fantasy Novel', 17.99, 'BOOKS'),
('Coffee', 5.99, 'GROCERY'),
('Gaming Monitor', 299.99, 'ELECTRONICS'),
('Thriller Novel', 13.99, 'BOOKS'),
('Rice', 3.99, 'GROCERY'),
('Gaming Chair', 199.99, 'ELECTRONICS');